name: pomodori
load: lib/main.rb
version: "0.2 beta © reborg@reborg.net"
icon: resources/pomodori.icns
resources:
  - resources/**/*.*
sources: 
  - lib/**/*.rb
  - resources/**/*.html
  - resources/**/*.css
  